// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDeKbAyaffg1bFsB0MaYOoW2MII6dIPmA',
    appId: '1:200518252364:web:ec36ed75e649afb02441e9',
    messagingSenderId: '200518252364',
    projectId: 'bamtol-market-app-son',
    authDomain: 'bamtol-market-app-son.firebaseapp.com',
    storageBucket: 'bamtol-market-app-son.firebasestorage.app',
    measurementId: 'G-YPKK3KNCVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBShyPVuEFzrn-pOT-P1kC3FM3jAIrdt54',
    appId: '1:200518252364:android:67f28ea3848e891f2441e9',
    messagingSenderId: '200518252364',
    projectId: 'bamtol-market-app-son',
    storageBucket: 'bamtol-market-app-son.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs8gvo73wfeQbW9bCGPu4ya25CVXhyQQ0',
    appId: '1:200518252364:ios:903d0841069a24a92441e9',
    messagingSenderId: '200518252364',
    projectId: 'bamtol-market-app-son',
    storageBucket: 'bamtol-market-app-son.firebasestorage.app',
    iosBundleId: 'com.devman.cloneapp.bamtolMarketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs8gvo73wfeQbW9bCGPu4ya25CVXhyQQ0',
    appId: '1:200518252364:ios:903d0841069a24a92441e9',
    messagingSenderId: '200518252364',
    projectId: 'bamtol-market-app-son',
    storageBucket: 'bamtol-market-app-son.firebasestorage.app',
    iosBundleId: 'com.devman.cloneapp.bamtolMarketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDeKbAyaffg1bFsB0MaYOoW2MII6dIPmA',
    appId: '1:200518252364:web:7f32caf6b2ef9aa82441e9',
    messagingSenderId: '200518252364',
    projectId: 'bamtol-market-app-son',
    authDomain: 'bamtol-market-app-son.firebaseapp.com',
    storageBucket: 'bamtol-market-app-son.firebasestorage.app',
    measurementId: 'G-LT3FKGD5Q1',
  );

}